category: "Sequence Analysis"
description: CLSI profile using MIC breakpoints
homepage_url: https://github.com/rakesh4osdd/asist/tree/main
long_description: CLSI profile using MIC breakpoints for bacteria from CLSI AST profiling 
name: clsi_profile
owner: rakesh4osdd
remote_repository_url: https://github.com/rakesh4osdd/asist/tree/main

category: "Sequence Analysis"
description: Antimicrobial Susceptibility standards
homepage_url: https://github.com/rakesh4osdd/asist/tree/master
long_description: Antimicrobial Susceptibility standards from CLSI Profile
name: asist
owner: rakesh4osdd
remote_repository_url: https://github.com/rakesh4osdd/asist/tree/master
auto_tool_repositories:
    name_template: "{{ tool_id }}"
    description_template: "ASIST tool suite | {{ tool_id }}"
suite:
    category: "Sequence Analysis"
    name: "suite_asist_tools"
    description: ASIST tools helps to find the phenotypes of strains from its CLSI standards based AST profiling
