categories: []
description: CLSI profile using MIC breakpoints
homepage_url: https://github.com/rakesh4osdd/clsi_profile/tree/master
long_description: CLSI profile using MIC breakpoints for bacteria
name: clsi_profile
owner: rakesh4osdd
remote_repository_url: https://github.com/rakesh4osdd/clsi_profile/tree/master
